plugins { id 'com.android.application' }

android {
    namespace 'com.beomsoo.sentenceapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.beomsoo.sentenceapp'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '2.1-syncfix'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
