const $=s=>document.querySelector(s);let lang="ko",busy=false,lastResult=null;
const api=async(path,opt)=>{const r=await fetch(path,opt);const j=await r.json();if(!r.ok)throw j;return j};
function pickLang(v){if(v==="auto")return navigator.language.startsWith("ko")?"ko":"en";return v}function tr(k){return I18N[lang][k]||k}function applyLang(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=tr(e.dataset.i18n))}
function service(name,v){return `<div class="service"><span class="service-dot ${v.ready?'on':''}"></span><div><b>${name}</b><span class="${v.ready?'ok':'bad'}">${v.ready?tr('ready'):tr('offline')}</span></div></div>`}
function humanResult(r,action){if(r.status==='not_ready')return {tone:'warn',text:tr('needsSetup')};if(!r.ok)return {tone:'bad',text:tr('actionFailed')};if(action==='pull'&&String(r.stdout||'').toLowerCase().includes('already up to date'))return {tone:'ok',text:tr('alreadyCurrent')};return {tone:'ok',text:tr('actionDone')}}
function progressLabel(action){return tr({pull:'pulling',build:'building',test:'testing',deploy:'deploying',status:'checking'}[action]||'running')}
function showToast(result,action,title){const h=humanResult(result,action);lastResult={result,title,summary:h.text};const t=$('#toast');t.className=`toast show ${h.tone}`;t.innerHTML=`<div><strong>${h.tone==='ok'?'✓':'!' } ${h.text}</strong><span>${title}</span></div><button id="toastDetails">${tr('showDetails')}</button>`;$('#toastDetails').onclick=showDetails;setTimeout(()=>t.classList.remove('show'),5000)}
function showDetails(){if(!lastResult)return;$('#detailsTitle').textContent=lastResult.title;$('#detailsSummary').textContent=lastResult.summary;$('#detailsBody').textContent=JSON.stringify(lastResult.result,null,2);$('#details').showModal()}
async function load(){try{const [s,ps,a]=await Promise.all([api('/api/status'),api('/api/projects'),api('/api/activity')]);const entries=Object.entries(s);$('#services').innerHTML=entries.map(([k,v])=>service(k==='gemma'?'Gemma':k==='termux_api'?'Android':k.toUpperCase(),v)).join('');const ready=entries.filter(([,v])=>v.ready).length;$('#readyCount').textContent=`${ready}/${entries.length}`;$('#overall').textContent=ready===entries.length?tr('ready'):`${ready} ${tr('ready')}`;
$('#projects').innerHTML=ps.map(p=>`<article class="project"><div class="project-head"><div><span class="project-kicker">${p.type}</span><strong>${p.name}</strong></div><span class="project-state"><i></i>${tr('ready')}</span></div><div class="actions">${p.actions.map(x=>`<button data-project="${p.id}" data-action="${x}" class="${x==='pull'?'primary':''}">${tr(x)}</button>`).join('')}</div></article>`).join('');
$('#activity').innerHTML=a.length?a.map(x=>`<div class="activity-row"><span>${x.project}<small>${x.action}</small></span><span class="${x.ok?'ok':'bad'}">${x.ok?'✓':'!'}</span></div>`).join(''):`<div class="activity-row">${tr('noActivity')}</div>`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>run(b));}catch(e){$('#overall').textContent='API error';$('#overall').className='bad'}}
async function run(b){if(busy)return;busy=true;document.querySelectorAll('[data-action]').forEach(x=>x.disabled=true);const action=b.dataset.action,title=`${b.dataset.project} · ${tr(action)}`;$('.action-progress').classList.add('show');$('#progressText').textContent=progressLabel(action);try{const r=await api(`/api/projects/${b.dataset.project}/actions/${action}`,{method:'POST'});showToast(r,action,title)}catch(e){showToast(e,action,title)}finally{busy=false;$('.action-progress').classList.remove('show');document.querySelectorAll('[data-action]').forEach(x=>x.disabled=false);load()}}
$('#close').onclick=()=>$('#details').close();$('#refresh').onclick=load;$('#language').onchange=e=>{lang=pickLang(e.target.value);applyLang();load()};lang=pickLang('auto');applyLang();load();
